--COMPANY
INSERT INTO COMPANY (COMPANY_NAME,TELEPHONE,ADDRESS) VALUES ('NPI','09309090909','LEPSE 6');
INSERT INTO COMPANY (COMPANY_NAME,TELEPHONE,ADDRESS) VALUES ('NP','0909009090','STOLICHNOE');
--AUTHORITIES
INSERT INTO AUTHORITIES (AUTHORITY) VALUES ('ROLE_ADMIN');
INSERT INTO AUTHORITIES (AUTHORITY) VALUES ('ROLE_USER');
INSERT INTO AUTHORITIES (AUTHORITY) VALUES ('ROLE_SUPERUSER');

--USERS
INSERT INTO CONTACT_PERSON (USERNAME, PASSWORD, ENABLED,FIRSTNAME,SECONDNAME,DEPARTMENT,CREATOR,ID_COMPANY,ID_ROLE)
VALUES ('superuser@outlook.com','12345',TRUE,'TEST','TEST','TEST','ADMIN',1,3);

INSERT INTO CONTACT_PERSON (USERNAME, PASSWORD, ENABLED,FIRSTNAME,SECONDNAME,DEPARTMENT,CREATOR,ID_COMPANY,ID_ROLE)
VALUES ('superuser@outlook.com','12345',TRUE,'TEST','TEST','TEST','ADMIN',1,2);

INSERT INTO CONTACT_PERSON (USERNAME, PASSWORD, ENABLED,FIRSTNAME,SECONDNAME,DEPARTMENT,CREATOR,ID_COMPANY,ID_ROLE)
VALUES ('superuser@outlook.com','12345',TRUE,'TEST','TEST','TEST','ADMIN',1,1);

--CONTACTS_DICTONARY
INSERT INTO D_CONTACT_TYPE (NAME) VALUES ('SMS');
INSERT INTO D_CONTACT_TYPE (NAME) VALUES ('VIBER');
INSERT INTO D_CONTACT_TYPE (NAME) VALUES ('TELEPHONE');
INSERT INTO D_CONTACT_TYPE (NAME) VALUES ('HERNIA');



--CONTACTS_CONTACT_PERSON
INSERT INTO CONTACTS_CONTACT_PERSON (id_contact_person,id_company,id_contact_type,priority_callback) VALUES (1,1,1,1);
INSERT INTO CONTACTS_CONTACT_PERSON (id_contact_person,id_company,id_contact_type,priority_callback) VALUES (1,1,2,1);
INSERT INTO CONTACTS_CONTACT_PERSON (id_contact_person,id_company,id_contact_type,priority_callback) VALUES (1,1,3,1);
INSERT INTO CONTACTS_CONTACT_PERSON (id_contact_person,id_company,id_contact_type,priority_callback) VALUES (2,1,1,1);


-- DUCTS
INSERT INTO D_DUCT (NAME_DUCT,DUCT_PRIORITY) VALUES ('PUSH',1);
INSERT INTO D_DUCT (NAME_DUCT,DUCT_PRIORITY) VALUES ('SMS',3);
INSERT INTO D_DUCT (NAME_DUCT,DUCT_PRIORITY) VALUES ('VIBER',2);


--STENCIL
INSERT INTO STENCIL (ID_D_DUCT,STENCIL_ENTITY) VALUES (1,'ASD #NAME QWE #VALUE');
INSERT INTO STENCIL (ID_D_DUCT,STENCIL_ENTITY) VALUES (2,'ASD #NAME QWE #VALUE');
INSERT INTO STENCIL (ID_D_DUCT,STENCIL_ENTITY) VALUES (3,'ASD #NAME QWE #VALUE');

--STRUCTURE
INSERT INTO STRUCTURE (ID_COMPANY,ID_STENCIL) VALUES(1,1);
INSERT INTO STRUCTURE (ID_COMPANY,ID_STENCIL) VALUES(1,2);


--message

insert into message (priority,frequence,delay,departuretime,relevanttime,duct,message,address) values (1,NOW(),NOW(),NOW(),NOW(),'{asd,asd}','messs','addr');
insert into message (priority,frequence,delay,departuretime,relevanttime,duct,message,address) values (1,NOW(),NOW(),NOW(),NOW(),'{asd,asd}','messs','addr');
insert into message (priority,frequence,delay,departuretime,relevanttime,duct,message,address) values (1,NOW(),NOW(),NOW(),NOW(),'{asd,asd}','messs','addr');